PMS_HT/Controllers/CityLedgerController.cs
using PMS_HT.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace PMS_HT.Controllers
{
    [Authorize(Roles = "Super Admin,Admin,Manager,Frontdesk")]
    public class CityLedgerController : CustomControllerBase
    {
        FrontDeskGuestStayController GStay = new FrontDeskGuestStayController();
        public ActionResult Index()
        {
            var query = "SELECT tbl_room_info.Room_No, tbl_guest_info.Name, tbl_guest_info.Phone, tbl_guest_info.Address, tbl_room_transactions.Credit, tbl_guest_stay_info.Arrival_Date, isnull(DATEADD(SECOND,DATEDIFF(SECOND,0,tbl_guest_stay_info.Check_Out_Time),tbl_guest_stay_info.Check_Out_Date),tbl_guest_stay_info.Departure_Date) AS Checkout_Date, tbl_room_transactions.Particulars, tbl_guest_stay_info.Stay_Info_ID FROM tbl_guest_stay_info INNER JOIN tbl_room_transactions ON tbl_guest_stay_info.Stay_Info_ID = tbl_room_transactions.Stay_Info_ID INNER JOIN tbl_room_info ON tbl_guest_stay_info.Room_ID = tbl_room_info.Room_ID INNER JOIN tbl_guest_info ON tbl_guest_stay_info.Guest_ID = tbl_guest_info.Guest_ID where tbl_guest_stay_info.Check_Out_Note LIKE '%Outstanding' AND tbl_room_transactions.Tran_Ref_ID = 11 ORDER BY Checkout_Date";
            var data = db.Database.SqlQuery<OutStandingViewModel>(query);
            List<OutStandingViewModel> tempList = data.ToList();

            ViewBag.OutStandingList = tempList;
            return View();
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var guest1 = db.tbl_guest_stay_info.FirstOrDefault(a => a.Stay_Info_ID == id && a.Status == "Clear");
            if (guest1 != null)
            {
                decimal roomCharge = 0, vat = 0, discount = 0, paid = 0, otherBill = 0, refund = 0, roomPayment = 0, roomVat = 0, roomDiscount = 0, roomOtherBill = 0, selectedRoomCharge = 0, roomDue = 0, outstand_charge = 0;

                ViewBag.GuestName = guest1.tbl_guest_info.Name;
                ViewBag.Phone = guest1.tbl_guest_info.Phone;
                ViewBag.Address = guest1.tbl_guest_info.Address;
                ViewBag.ArrivalDate = guest1.Arrival_Date;
                ViewBag.DepartureDate = guest1.Departure_Date;
                DateTime checkOutDateTime = guest1.Check_Out_Date.Value;
                checkOutDateTime = checkOutDateTime.Add(guest1.Check_Out_Time.Value);
                ViewBag.checkOutDateTime = checkOutDateTime;
                ViewBag.id = id;

                double noOfNight = GStay.StayDayCalculator(guest1.Arrival_Date, checkOutDateTime);

                ViewBag.NoOfNight = noOfNight;
                ViewBag.RoomChargePerDayS = guest1.tbl_room_info.Rate;


                //var roomChargesS = db.tbl_room_transactions.Where(a => a.Stay_Info_ID == (guest1.Stay_Info_ID) && (a.Tran_Ref_ID == 4 || a.Tran_Ref_ID == 16)).ToList();
                //ViewBag.RoomChargeListS = roomChargesS;
                //if (roomChargesS != null)
                //{
                //    foreach (var item in roomChargesS)
                //    {
                //        if (item.Tran_Date.Value.Date == guest1.Arrival_Date.Date ||
                //            item.Tran_Date.Value.AddHours(3) < checkOutDateTime)
                //        {
                //            roomCharge += (decimal) item.Debit;
                //        }
                //    }
                //}
                //ViewBag.RoomChargeS = roomCharge;

                var vats = db.tbl_room_transactions.Where(a => a.Stay_Info_ID == (guest1.Stay_Info_ID) && (a.Tran_Ref_ID == 2 || a.Tran_Ref_ID == 15)).ToList();
                if (vats != null)
                {
                    foreach (var item in vats)
                    {
                        if (item.Tran_Date.Value.Date == guest1.Arrival_Date.Date || item.Tran_Date.Value.AddHours(3) < checkOutDateTime)
                        {
                            vat += (decimal)item.Debit;
                        }
                    }
                }
                ViewBag.Vat = vat;
                ViewBag.RoomVat = roomVat;
                ViewBag.VatPercent = 0;

                var discounts = db.tbl_room_transactions.Where(a => a.Stay_Info_ID == (guest1.Stay_Info_ID) && (a.Tran_Ref_ID == 1)).ToList();
                ViewBag.DiscountList = discounts;
                if (discounts != null && discounts.Count != 0)
                {
                    foreach (var item in discounts)
                    {
                        discount += (decimal)item.Credit;
                    }
                }
                ViewBag.Discount = discount;

                var otherBillsS = db.tbl_room_transactions.Where(a => a.Stay_Info_ID == (guest1.Stay_Info_ID) && (a.Tran_Ref_ID == 5 || a.Tran_Ref_ID == 6)).ToList();
                ViewBag.OtherBillListS = otherBillsS;
                if (otherBillsS != null)
                {
                    foreach (var item in otherBillsS)
                    {
                        otherBill += (decimal)item.Debit;
                    }
                }
                ViewBag.OtherBillS = otherBill;

                var refunds = db.tbl_room_transactions.Where(a => a.Stay_Info_ID == (guest1.Stay_Info_ID) && (a.Tran_Ref_ID == 7)).ToList();
                if (refunds != null)
                {
                    foreach (var item in refunds)
                    {
                        refund += (decimal)item.Credit;
                    }
                }
                ViewBag.refund = refund;

                var paidTransactionsS = db.tbl_room_transactions.Where(a => a.Stay_Info_ID == (guest1.Stay_Info_ID) && (a.Tran_Ref_ID == 3 || a.Tran_Ref_ID == 12 || a.Tran_Ref_ID == 14)).ToList();
                ViewBag.paidTransactionsS = paidTransactionsS;
                if (paidTransactionsS != null)
                {
                    foreach (var item in paidTransactionsS)
                    {
                        paid += (decimal)item.Credit;
                    }
                }
                ViewBag.PaidS = paid;

                tbl_room_transactions outRow = db.tbl_room_transactions.FirstOrDefault(a => a.Stay_Info_ID == (guest1.Stay_Info_ID) && a.Tran_Ref_ID == 11);
                if (outRow != null)
                {
                    outstand_charge += (decimal)outRow.Credit;
                }

                //roomDue = (roomCharge + vat + otherBill) - (paid + discount);

                roomDue = outstand_charge;
                roomCharge = (roomDue + paid + discount) - (vat + otherBill);
                ViewBag.RoomChargeS = roomCharge;
                ViewBag.RoomTotalCharge = (roomCharge + vat + otherBill) - discount;
                ViewBag.RoomDueS = roomDue;
                return PartialView();
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(int stayId, decimal paid, string particulars, decimal netPayable)
        {
            if (ModelState.IsValid)
            {
                var tblEmpInfo = db.tbl_emp_info.FirstOrDefault(a => a.user_name == User.Identity.Name);
                if (tblEmpInfo != null)
                {
                    var guest1 = db.tbl_guest_stay_info.FirstOrDefault(a => a.Stay_Info_ID == stayId);
                    if (guest1 != null)
                    {
                        bool isFullPaid = false;
                        tbl_guest_attendee attendee = new tbl_guest_attendee();
                        attendee.Emp_ID = tblEmpInfo.Emp_ID;
                        attendee.Purpose = "Outstanding Payment";
                        attendee.Changed_Date = DateTime.Now;
                        attendee.Stay_Info_ID = guest1.Stay_Info_ID;
                        db.tbl_guest_attendee.Add(attendee);

                        tbl_room_transactions paidTransaction = new tbl_room_transactions();
                        paidTransaction.Stay_Info_ID = guest1.Stay_Info_ID;
                        paidTransaction.Room_ID = guest1.Room_ID;
                        paidTransaction.Guest_ID = guest1.Guest_ID;
                        paidTransaction.Debit = 0;
                        paidTransaction.Emp_ID = tblEmpInfo.Emp_ID;
                        paidTransaction.Particulars = particulars;
                        paidTransaction.Tran_Date = DateTime.Now;

                        tbl_room_transactions outRow = db.tbl_room_transactions.FirstOrDefault(a => a.Stay_Info_ID == stayId && a.Tran_Ref_ID == 11);
                        if (outRow != null)
                        {
                            if (paid != 0)
                            {
                                if (paid < netPayable)
                                {
                                    paidTransaction.Credit = paid;
                                    paidTransaction.Tran_Ref_ID = 12;
                                    paidTransaction.Tran_Ref_Name = "OutStanding Paid";
                                    db.tbl_room_transactions.Add(paidTransaction);

                                    outRow.Credit = netPayable - paid;
                                    db.tbl_room_transactions.Attach(outRow);
                                    var updatedOutRow = db.Entry(outRow);
                                    updatedOutRow.State = EntityState.Modified;
                                }
                                else if (paid > netPayable)
                                {
                                    paidTransaction.Credit = paid;
                                    paidTransaction.Tran_Ref_ID = 12;
                                    paidTransaction.Tran_Ref_Name = "OutStanding Paid";
                                    db.tbl_room_transactions.Add(paidTransaction);
                                    db.SaveChanges();

                                    outRow.Credit = 0;

PMS_HT/Views/CityLedger/Edit.cshtml
@model  tbl_guest_stay_info
@using PMS_HT.Models

<style>
    label.error {
        color: red;
        font-style: italic;
    }
</style>

@{
    List<tbl_room_transactions> otherBillList = ViewBag.OtherBillListS;
    List<tbl_room_transactions> discountList = ViewBag.DiscountList;
    List<tbl_room_transactions> paidList = ViewBag.paidTransactionsS;
}
@using (Ajax.BeginForm("Edit", "CityLedger", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "div-record", OnSuccess = "$('.close').click()" }, new { id = "CheckOutForm" }))
{
    <div class="form-horizontal">
        <br />
        <br />
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <input type="text" id="stayId" name="stayId" value="@ViewBag.id" hidden readonly />
        <div class="container-fluid">
            <div class="row form-group col-md-12 col-lg-12 col-sm-12 col-xs-12">
                <div class="portlet-body tabs-below">
                    <div class="tab-content">
                        <div class="row form-group">
                            <div class="form-group">
                                @Html.LabelFor(model => model.tbl_guest_info.Name, htmlAttributes: new { @class = "control-label col-md-1 col-sm-8 col-xs-8" })
                                <div class="col-md-3 col-sm-8 col-xs-8">
                                    <input type="text" name="Name" id="Name" readonly class="form-control" value="@ViewBag.GuestName">
                                </div>

                                @Html.LabelFor(model => model.tbl_guest_info.Phone, htmlAttributes: new { @class = "control-label col-md-1 col-sm-8 col-xs-8" })
                                <div class="col-md-3 col-sm-8 col-xs-8">
                                    <input type="text" name="Phone" id="Phone" readonly class="form-control" value="@ViewBag.Phone">
                                </div>

                                @Html.LabelFor(model => model.tbl_guest_info.Address, htmlAttributes: new { @class = "control-label col-md-1 col-sm-8 col-xs-8" })
                                <div class="col-md-3 col-sm-8 col-xs-8">
                                    <input type="text" name="Phone" id="Phone" readonly class="form-control" value="@ViewBag.Address">
                                </div>
                            </div>
                        </div>

                        <div class="row form-group">
                            <div class="form-group ">
                                @Html.LabelFor(model => model.Arrival_Date, "Arrival Date", htmlAttributes: new { @class = "control-label col-md-1 col-sm-2 col-xs-2" })
                                <div class="col-md-3 col-sm-4 col-xs-4">
                                    <input type="text" name="Arrival_Date" id="Arrival_Date" readonly class="form-control" value="@ViewBag.ArrivalDate">
                                </div>
                                @Html.LabelFor(model => model.Departure_Date, "Departure Date", htmlAttributes: new { @class = "control-label col-md-1 col-sm-2 col-xs-2" })
                                <div class="col-md-3 col-sm-4 col-xs-4">
                                    <input type="text" name="Departure_Date" id="Departure_Date" readonly class="form-control" value="@ViewBag.DepartureDate">
                                </div>
                                @Html.Label("checkOutDate", "CheckOut Date", htmlAttributes: new { @class = "control-label col-md-1 col-sm-2 col-xs-2" })
                                <div class="col-md-3 col-sm-4 col-xs-4">
                                    <input type="text" name="checkOutDate" id="checkOutDate" readonly class="form-control" value="@ViewBag.checkOutDateTime">
                                </div>
                            </div>
                        </div>

                        @*<div class="row form-group">
                            <div class="form-group ">
                                @Html.Label("roomRate", "Room Rate", htmlAttributes: new { @class = "control-label col-md-2 col-sm-2 col-xs-2" })
                                <div class="col-md-2 col-sm-4 col-xs-4">
                                    <input type="text" name="roomRate" id="roomRate" class="form-control" value="@ViewBag.RoomChargePerDayS" readonly>
                                </div>
                                @Html.Label("totalRoomCharge", "Total Room Charge", htmlAttributes: new { @class = "control-label col-md-2 col-sm-2 col-xs-2" })
                                <div class="col-md-2 col-sm-4 col-xs-4">
                                    <input type="text" name="totalRoomCharge" id="totalRoomCharge" class="form-control" value="@ViewBag.RoomChargeS" readonly>
                                </div>
                                @Html.Label("vat", "Total Vat", htmlAttributes: new { @class = "control-label col-md-2 col-sm-2 col-xs-2 ", id = "vatLabel" })
                                <div class="col-md-2 col-sm-4 col-xs-4">
                                    <input type="text" name="vat" id="vat" class="form-control" readonly value="@ViewBag.Vat">
                                </div>
                            </div>
                        </div>

                        <div class="row form-group">
                            <div class="form-group">
                                @Html.Label("discount", "Discount", htmlAttributes: new { @class = "control-label col-md-2 col-sm-2 col-xs-2", id = "discountLabel" })
                                <div class="col-md-2 col-sm-4 col-xs-4">
                                    <input type="text" name="discount" id="discount" class="form-control" value="@ViewBag.Discount" readonly>
                                </div>
                                @Html.Label("otherBill", "Other Bill", htmlAttributes: new { @class = "control-label col-md-2 col-sm-2 col-xs-2" })
                                <div class="col-md-2 col-sm-4 col-xs-4">
                                    <input type="text" name="otherBill" id="otherBill" class="form-control" readonly value="@ViewBag.OtherBillS">
                                </div>
                                @Html.Label("totalCharge", "Total Charge (Rounded)", htmlAttributes: new { @class = "control-label col-md-2 col-sm-2 col-xs-2" })
                                <div class="col-md-2 col-sm-4 col-xs-4">
                                    <input type="text" name="totalCharge" id="totalCharge" class="form-control" readonly>
                                </div>
                            </div>
                        </div>

                        <div class="row form-group">
                            <div class="form-group">
                                @Html.Label("previousPaid", "Previous Paid", htmlAttributes: new { @class = "control-label col-md-2 col-sm-2 col-xs-2" })
                                <div class="col-md-2 col-sm-4 col-xs-4">
                                    <input type="text" name="previousPaid" id="previousPaid" class="form-control" value="@ViewBag.PaidS" readonly>
                                </div>
                                @Html.Label("due", "Outstand Charge", htmlAttributes: new { @class = "control-label col-md-2 col-sm-2 col-xs-2" })
                                <div class="col-md-2 col-sm-4 col-xs-4">
                                    <input type="text" name="due" id="due" readonly class="form-control">
                                </div>
                            </div>
                        </div>*@
                            
                        <label><strong>Payment: </strong></label>
                        <div class="row form-group">
                            <div class="form-group">
                                @Html.Label("netPayable", "Net Payable", htmlAttributes: new { @class = "control-label col-md-2 col-sm-2 col-xs-2" })
                                <div class="col-md-2 col-sm-4 col-xs-4">
                                    <input type="text" name="netPayable" id="netPayable" class="form-control" value="@ViewBag.RoomDueS" readonly>
                                </div>
                                @Html.Label("paid", "Paid", htmlAttributes: new { @class = "control-label col-md-2 col-sm-2 col-xs-2" })
                                <div class="col-md-2 col-sm-4 col-xs-4">
                                    <input type="text" name="paid" id="paid" onkeyup="GetNetPayable()" onchange="GetNetPayable()" class="form-control">
                                </div>
                                @Html.Label("particulars", "Particulars", htmlAttributes: new { @class = "control-label col-md-2 col-sm-2 col-xs-2" })
                                <div class="col-md-2 col-sm-4 col-xs-4">
                                    <input type="text" name="particulars" id="particulars" onkeyup="GetNetPayable()" onchange="GetNetPayable()" class="form-control">
                                </div>
                            </div>
                        </div>

                        <div class="row form-group">                                
                            <div class="form-group" style="float:right; padding-right:20px">
                                <div class="col-md-offset-2 col-md-4 col-sm-8 col-xs-8">
                                    <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i>&nbsp;Close</button>
                                </div>
                                <div class="col-md-offset-2 col-md-4 col-sm-8 col-xs-8">
                                    <button type="button" value="Pay" class="btn btn-success" onclick="CheckPaidDue()"><i class="fa fa-credit-card" aria-hidden="true"></i> Pay</button>
                                </div>
                            </div>
                        </div>                         
                    </div>
                </div>  
            </div>
        </div>
    </div>
}

<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/MathRound10.js"></script>

<script>
    $(document).ready(function () {
        @*var roomTotalCharge = '@ViewBag.RoomTotalCharge';
        roomTotalCharge = Math.round10(roomTotalCharge, 1);
        var due = '@ViewBag.RoomDueS';
        due = Math.round10(due, 1);
        $("#totalCharge").val(roomTotalCharge);
        $("#due").val(due);
        $("#netPayable").val(due);
        var vatPercent = '@(ViewBag.VatPercent)';*@
    });

    function CheckPaidDue()
    {
        var paid = Number($("#paid").val());
        var netPayable = Number($("#netPayable").val());
        if(paid >= netPayable)
        {
            $("#CheckOutForm").submit();
        }
        else
        {
            if (confirm("Paid amount is less then Net Payable amount.\nProceed as Outstanding?")) {
                $("#CheckOutForm").submit();
            }
        }
    }

    $('#CheckOutForm').validate({
        rules: {
            paid: {
                required: true,
                number: true
            },
            particulars: "required"
        },
        messages: {
            paid: {
                required: "Paid field can not be empty",
                number: "Paid amount must be a number"
            },
            particulars: "This field can not be empty !"
        }
    });



</script>

PMS_HT/Views/CityLedger/Index.cshtml
@model OutStandingViewModel
@using PMS_HT.Models

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var i = 0;
    decimal total = 0;
}

<script src="~/Scripts/AddViewModel.js"></script>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="portlet box green">
                <div class="portlet-title">
                    <div class="caption">
                        City Ledger
                    </div>
                    <div class="tools">

                    </div>
                </div>
                <div class="portlet-body">
                    <table class="table table-striped table-bordered table-hover" id="sample_2">
                        <thead>
                        <tr>
                            <th>SL. No</th>
                            <th>Room No</th>
                            <th>Name</th>
                            <th>Phone</th>
                            <th>Address</th>
                            <th>Arrival Date</th>
                            <th>CheckOut Date</th>
                            <th>Amount</th>
                            <th>Pay</th>
                        </tr>
                        </thead>
                        <tbody>
                        @if (ViewBag.OutStandingList != null)
                        {
                            foreach (var item in ViewBag.OutStandingList)
                            {
                                <tr>
                                    <td>
                                        @{i++; total += item.Credit;}
                                        @i
                                    </td>
                                    <td>
                                        @item.Room_No
                                    </td>
                                    <td>
                                        @item.Name
                                    </td>
                                    <td>
                                        @item.Phone
                                    </td>
                                    <td>
                                        @item.Address
                                    </td>
                                    <td>
                                        @item.Arrival_Date
                                    </td>
                                    <td>
                                    @item.Checkout_Date
                                    <td>
                                        @item.Credit
                                    </td>
                                    <td style="text-align:center;">
                                        <a href="@Url.Action("Edit", "CityLedger", new { id = item.Stay_Info_ID })" class="editDialog" data-toggle="tooltip" title="View"><i class="fa fa-credit-card"  style="transform:scale(2);"></i></a>
                                    </td>
                                </tr>
                            }
                        }

                        </tbody>

                    </table>
                </div>
                <div style="width:100%">
                    <h3 style="font-weight:700;text-align:center;">Total Amount : ৳ @total</h3>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade bs-modal-lg in" id="Edit-Model" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Credit Payment</h4>
            </div>
            <div class="divForUpdate">
            </div>
        </div>
    </div>
</div>

<script>
    $('.editDialog').click(function (event) {
        event.preventDefault();
        $.get(this.href, function (response) {
            $('.divForUpdate').html(response);
        });
        $('#Edit-Model').modal({
            backdrop: 'static',
        }, 'show');
    });
</script>