PMS_HT/Controllers/PayRollSalaryEarningController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using PMS_HT.Models;

namespace PMS_HT.Controllers
{
    public class PayRollSalaryEarningController : CustomControllerBase
    {
        public ActionResult Index(int? id)
        {
            var tbl_salary_transactions = db.tbl_salary_transactions.Where(a => a.Tran_Ref_Name.Equals("SalaryEarning") && a.Emp_ID == id).Include(t => t.tbl_earning_head).Include(t => t.tbl_emp_info);
            ViewBag.EmpId = id;
            Session["EmployeeId"] = id;
            return View(tbl_salary_transactions.ToList());
        }

        public ActionResult Add(int? id)
        {
            ViewBag.Tran_Ref_ID = new SelectList(db.tbl_earning_head.Where(a => a.Type.Equals("Earning")), "Earning_Head_ID", "Earning_Head_Name");
            ViewBag.Emp_ID = id;
            return PartialView();
        }

        [HttpPost]
        public ActionResult Add(tbl_salary_transactions empSalaryDeduction)
        {
            int parameter = Convert.ToInt32(Session["EmployeeId"]);
            if (ModelState.IsValid)
            {
                empSalaryDeduction.Emp_ID = parameter;      
                empSalaryDeduction.Tran_Ref_Name = "SalaryEarning";   
                db.tbl_salary_transactions.Add(empSalaryDeduction);
                db.SaveChanges();
            }
            ViewBag.Tran_Ref_ID = new SelectList(db.tbl_earning_head, "Earning_Head_ID", "Earning_Head_Name", empSalaryDeduction.Tran_Ref_ID);
            ViewBag.Emp_ID = new SelectList(db.tbl_emp_info, "Emp_ID", "Emp_Name", empSalaryDeduction.Emp_ID);
            return RedirectToAction("Index", new { id = parameter });
        }

        public ActionResult Delete(int id)
        {
            int parameter = Convert.ToInt32(Session["EmployeeId"]);
            db.tbl_salary_transactions.Remove(db.tbl_salary_transactions.Find(id));
            db.SaveChanges();
            return RedirectToAction("Index", new { id = parameter});
        }

        public ActionResult Edit(int id)
        {          
            tbl_salary_transactions salary = db.tbl_salary_transactions.Find(id);
            ViewBag.Tran_Ref_ID = new SelectList(db.tbl_earning_head.Where(a=> a.Type.Equals("Earning")), "Earning_Head_ID", "Earning_Head_Name", salary.Tran_Ref_ID);
            ViewBag.Emp_ID = new SelectList(db.tbl_emp_info, "Emp_ID", "Emp_Name", salary.Emp_ID);
            return PartialView(salary);
        }

        [HttpPost]
        public ActionResult Edit(tbl_salary_transactions salary, int id)
        {
            int parameter = Convert.ToInt32(Session["EmployeeId"]);
            if (ModelState.IsValid)
            {
                salary.Emp_ID = parameter;
                salary.Tran_Ref_Name = "SalaryEarning";
                db.Entry(salary).State = EntityState.Modified;
                db.SaveChanges();
            }
            ViewBag.Tran_Ref_ID = new SelectList(db.tbl_earning_head, "Earning_Head_ID", "Earning_Head_Name", salary.Tran_Ref_ID);
            ViewBag.Emp_ID = new SelectList(db.tbl_emp_info, "Emp_ID", "Emp_Name", salary.Emp_ID);
            return RedirectToAction("Index", new { id = parameter });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PMS_HT/Views/PayRollSalaryEarning/Add.cshtml
@model PMS_HT.Models.tbl_salary_transactions

<script type="text/javascript">

    $(function () {
        $(".datefield").datepicker({ dateFormat: 'dd/mm/yy' });
    });
</script>

@using (Ajax.BeginForm("Add", "PayRollSalaryEarning", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "div-record", OnSuccess = "$('.close').click()" }))
{
    <div class="form-horizontal">
        <div class="modal-body">
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row">
                @Html.HiddenFor(model => model.Emp_ID, new { @Value = ViewBag.Emp_ID })
                <div class="form-group">
                    @Html.LabelFor(model => model.Tran_Ref_ID, "Earning", htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-8">
                        @Html.DropDownList("Tran_Ref_ID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Tran_Ref_ID, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Particular, "Particular", htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Particular, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Particular, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Debit, "Amount", htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Debit, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Debit, "", new { @class = "text-danger" })
                    </div>
                </div>


                @*<div class="form-group">
                        <div class="col-md-3">
                            @Html.Label("Month")
                        </div>
                        <div class="col-md-9">
                            @Html.EditorFor(model => model.Month_Name, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Month_Name, "", new { @class = "text-danger" })
                        </div>
                    </div>*@


                <div class="form-group">
                    <div class="control-label col-md-3">Month</div>
                    <div class="col-md-8">
                        <select id="Month_Name" name="Month_Name" class="form-control ">
                            <option>January</option>
                            <option>February</option>
                            <option>March</option>
                            <option>April</option>
                            <option>May</option>
                            <option>June</option>
                            <option>July</option>
                            <option>August</option>
                            <option>September</option>
                            <option>October</option>
                            <option>November</option>
                            <option>December</option>
                        </select>
                        @Html.ValidationMessageFor(model => model.Month_Name)
                    </div>

                </div>

                <div class="form-group">
                        @Html.LabelFor(model => model.Year_Name, "Year Name", htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-8">
                        @Html.ValidationMessageFor(model => model.Year_Name, "", new { @class = "text-danger" })

                        <select id="Year_Name" name="Year_Name" class="form-control">
                            @for (var i = 0; i < 6; i++)
                        {
                            <option>@(DateTime.Now.AddYears(i).Year)</option>
                        }
                        </select>
                    </div>
                </div>

                <div class="form-group">
                        @Html.LabelFor(model => model.Date, "Date", htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control datefield" } })
                        @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i>&nbsp;Close</button>
        <button type="submit" class="btn btn-success" name="cmd"><i class="fa fa-check"></i>&nbsp;Save</button>
    </div>
}

PMS_HT/Views/PayRollSalaryEarning/Delete.cshtml
@model PMS_HT.Models.tbl_salary_transactions

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tbl_salary_transactions</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.tbl_earning_head.Earning_Head_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_earning_head.Earning_Head_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tbl_emp_info.Emp_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_emp_info.Emp_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Particular)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Particular)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tran_Ref_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tran_Ref_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Debit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Debit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Credit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Credit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Balance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Balance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Month_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Month_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

PMS_HT/Views/PayRollSalaryEarning/Details.cshtml
@model PMS_HT.Models.tbl_salary_transactions

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>tbl_salary_transactions</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.tbl_earning_head.Earning_Head_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_earning_head.Earning_Head_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tbl_emp_info.Emp_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_emp_info.Emp_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Particular)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Particular)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tran_Ref_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tran_Ref_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Debit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Debit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Credit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Credit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Balance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Balance)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Month_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Month_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Year_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Year_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Date)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Salary_Tran_ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PMS_HT/Views/PayRollSalaryEarning/Edit.cshtml
@model PMS_HT.Models.tbl_salary_transactions


<script type="text/javascript">

    $(function () {
        $(".datefield").datepicker({ dateFormat: 'dd/mm/yy' });
    });
</script>

@using (Ajax.BeginForm("Edit", "PayRollSalaryEarning", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "div-record", OnSuccess = "$('.close').click()" }))
{
    @Html.HiddenFor(m => m.Salary_Tran_ID)
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-horizontal">
    <div class="modal-body">
        <div class="row form-group">

            <div class="form-group">
                @Html.LabelFor(model => model.Tran_Ref_ID, "Earning", htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-8">
                    @Html.DropDownList("Tran_Ref_ID", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Tran_Ref_ID, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.Particular, "Particular", htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Particular, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Particular, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                    @Html.LabelFor(model => model.Debit, "Amount", htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Debit, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Credit, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Month_Name, "Month Name", htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-8">
                    @{var Month_Name = new List<SelectListItem>
                        {
                        new SelectListItem { Text = "January", Value="January" },
                        new SelectListItem { Text = "February", Value="February" },
                        new SelectListItem { Text = "March", Value="March" },
                        new SelectListItem { Text = "April", Value="April" },
                        new SelectListItem { Text = "May", Value="May" },
                        new SelectListItem { Text = "June", Value="June" },
                        new SelectListItem { Text = "July", Value="July" },
                        new SelectListItem { Text = "August", Value="August" },
                        new SelectListItem { Text = "September", Value="September" },
                        new SelectListItem { Text = "October", Value="October" },
                        new SelectListItem { Text = "November", Value="November" },
                        new SelectListItem { Text = "December", Value="December" }
                        };
                    }
                    @Html.DropDownList("Month_Name", new SelectList(Month_Name, "Value", "Text"), htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Month_Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Year_Name, "Year Name", htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-8">                  
                    @{ 
                        var Year_Name = new List<SelectListItem>();
                        for (int i = 0; i <= 6; i++)
                        {
                            Year_Name.Add(new SelectListItem
                            {
                                Value = DateTime.Now.AddYears(i).Year.ToString(),
                                Text = DateTime.Now.AddYears(i).Year.ToString()
                            });
                        }
                    }
                   @Html.DropDownList("Year_Name", new SelectList(Year_Name, "Value", "Text"), htmlAttributes: new { @class = "form-control" })
                   @Html.ValidationMessageFor(model => model.Year_Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Date, "Date", htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-8">
                    @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control datefield" } })
                    @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i>&nbsp;Close</button>
        <button type="submit" class="btn btn-success" name="cmd"><i class="fa fa-check"></i>&nbsp;Save Changes</button>
    </div>
}

PMS_HT/Views/PayRollSalaryEarning/Index.cshtml
@model IEnumerable<PMS_HT.Models.tbl_salary_transactions>

@{
    ViewBag.Title = "Salary Earning";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/AddViewModel.js"></script>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="portlet box green">
                <div class="portlet-title">
                    <div class="caption">
                        <a href="@Url.Action("Add", "PayRollSalaryEarning", new { id = ViewBag.EmpId})" id="Add" class="btn default"><i class="glyphicon glyphicon-plus"></i>&nbsp;Create New</a>
                        Employee
                    </div>
                    <div class="tools">

                    </div>
                </div>
                <div class="portlet-body">
                    <table class="table table-striped table-bordered table-hover" id="sample_2">
                        <thead>
                            <tr>
                                <th>SL No </th>
                                <th>Earning Heading</th>
                                <th>Employee Name</th>
                                <th>Particular</th>
                                <th>Amount</th>
                                <th>Month Name</th>
                                <th>Year Name</th>
                                <th>Date</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{ int i = 0;}
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @{i++;}
                                        @i
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.tbl_earning_head.Earning_Head_Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.tbl_emp_info.Emp_Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Particular)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Debit)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Month_Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Year_Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Date)
                                    </td>
                                    <td>
                                        <a href="@Url.Action("Edit", "PayRollSalaryEarning", new { id = item.Salary_Tran_ID })" class="editDialog"><i class="fa fa-pencil-square-o"></i>&nbsp;Edit</a>
                                    </td>
                                    <td>
                                        @Ajax.ActionLink(" Delete", "Delete", "PayRollSalaryEarning", new { @id = item.Salary_Tran_ID }, new AjaxOptions { HttpMethod = "GET", UpdateTargetId = "div-record" }, new { onclick = "return confirm('Are you sure you wish to delete this Salary Earning?');", @class = "fa fa-trash-o" })
                                    </td>
                                </tr>
                                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="Add-Model" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">New Payroll Salary Earning</h4>
            </div>
            <div class="divForAdd">
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="Edit-Model" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Update Earning</h4>
            </div>
            <div class="divForUpdate">
            </div>
        </div>
    </div>
</div>