PMS_HT/Controllers/InventoryItemController.cs
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using PMS_HT.Models;

namespace PMS_HT.Controllers
{
    public class InventoryItemController : CustomControllerBase
    {
        public ActionResult Index()
        {
            var tbl_item = db.tbl_item.Include(t => t.tbl_brand).Include(t => t.tbl_category).Include(t => t.tbl_subcategory).Include(t => t.tbl_unit);
            return View(tbl_item.ToList());
        }

        public ActionResult Add()
        {
            ViewBag.Brand_ID = new SelectList(db.tbl_brand, "Brand_ID", "Brand_Name");
            ViewBag.Cata_ID = new SelectList(db.tbl_category, "Cata_ID", "Cata_Name");
            int cata_id = db.tbl_category.FirstOrDefault().Cata_ID;
            ViewBag.Subcata_ID = new SelectList(db.tbl_subcategory.Where(a => a.Cata_ID == cata_id), "Subcata_ID", "Subcata_Name");
            ViewBag.Unit_ID = new SelectList(db.tbl_unit, "Unit_ID", "Unit_Name");
            return PartialView();
        }

        [HttpPost]
        public ActionResult Add(tbl_item item)
        {
            if (ModelState.IsValid)
            {
                db.tbl_item.Add(item);
                db.SaveChanges();
            }
            ViewBag.Brand_ID = new SelectList(db.tbl_brand, "Brand_ID", "Brand_Name", item.Brand_ID);
            ViewBag.Cata_ID = new SelectList(db.tbl_category, "Cata_ID", "Cata_Name", item.Cata_ID);
            ViewBag.Subcata_ID = new SelectList(db.tbl_subcategory, "Subcata_ID", "Subcata_Name", item.Subcata_ID);
            ViewBag.Unit_ID = new SelectList(db.tbl_unit, "Unit_ID", "Unit_Name", item.Unit_ID);
            return RedirectToAction("Items", "InventorySettings");
        }

        public ActionResult Edit(int id)
        {
            tbl_item item = db.tbl_item.Find(id);
            ViewBag.Brand_ID = new SelectList(db.tbl_brand, "Brand_ID", "Brand_Name", item.Brand_ID);
            ViewBag.Cata_ID = new SelectList(db.tbl_category, "Cata_ID", "Cata_Name", item.Cata_ID);
            ViewBag.Subcata_ID = new SelectList(db.tbl_subcategory, "Subcata_ID", "Subcata_Name", item.Subcata_ID);
            ViewBag.Unit_ID = new SelectList(db.tbl_unit, "Unit_ID", "Unit_Name", item.Unit_ID);
            return PartialView(item);
        }

        [HttpPost]
        public ActionResult Edit(tbl_item item, int id)
        {
            if (ModelState.IsValid)
            {
                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();
            }
            ViewBag.Brand_ID = new SelectList(db.tbl_brand, "Brand_ID", "Brand_Name", item.Brand_ID);
            ViewBag.Cata_ID = new SelectList(db.tbl_category, "Cata_ID", "Cata_Name", item.Cata_ID);
            ViewBag.Subcata_ID = new SelectList(db.tbl_subcategory, "Subcata_ID", "Subcata_Name", item.Subcata_ID);
            ViewBag.Unit_ID = new SelectList(db.tbl_unit, "Unit_ID", "Unit_Name", item.Unit_ID);
            return RedirectToAction("Items", "InventorySettings");
        }

        public ActionResult Delete(int id)
        {
            db.tbl_item.Remove(db.tbl_item.Find(id));
            db.SaveChanges();
            return RedirectToAction("Items", "InventorySettings");
        }

        public ActionResult FillSubCategory(int cata_id)
        {
            var subcategories = db.tbl_subcategory.Where(c => c.Cata_ID == cata_id).Select(c => new { Subcata_ID = c.Subcata_ID, Subcata_Name = c.Subcata_Name });
            return Json(subcategories, JsonRequestBehavior.AllowGet);
        }

        public ActionResult FillUnit(int item_id)
        {
            var item = db.tbl_item.FirstOrDefault(c => c.Item_ID == item_id);
            if (item != null)
            {
                var unit = item.tbl_unit.Unit_Name;
                return Json(unit, JsonRequestBehavior.AllowGet);
            }
            return Json("", JsonRequestBehavior.AllowGet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PMS_HT/Views/InventoryItem/Add.cshtml
@model PMS_HT.Models.tbl_item

@using (Ajax.BeginForm("Add", "InventoryItem", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "div-record", OnSuccess = "$('.close').click()" }, new { id = "itemAddForm" }))
{
    <div class="form-horizontal">
        <div class="modal-body">
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row">
                <div class="form-group">
                    @Html.LabelFor(model => model.Cata_ID, "Category", htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-8">
                        @Html.DropDownList("Cata_ID", null, htmlAttributes: new { @class = "form-control", @onchange = "FillSubCategory()" })
                        @Html.ValidationMessageFor(model => model.Cata_ID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Subcata_ID, "Sub Category", htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-8">
                        @Html.DropDownList("Subcata_ID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Subcata_ID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Brand_ID, "Brand ", htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-8">
                        @Html.DropDownList("Brand_ID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Brand_ID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Unit_ID, "Unit", htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-8">
                        @Html.DropDownList("Unit_ID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Unit_ID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Item_Name, "Item Name", htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Item_Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Item_Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                @*<div class="form-group">
                        @Html.LabelFor(model => model.Sales_Price, htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Sales_Price, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Sales_Price, "", new { @class = "text-danger" })
                        </div>
                    </div>*@

                @*<div class="form-group">
                        @Html.LabelFor(model => model.Purchase_Price,"Purchase Price", htmlAttributes: new { @class = "control-label col-md-3" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.Purchase_Price, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Purchase_Price, "", new { @class = "text-danger" })
                        </div>
                    </div>*@

                <div class="form-group">
                    @Html.LabelFor(model => model.Reorder_Level, "Reorder Lavel", htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Reorder_Level, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Reorder_Level, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i>&nbsp;Close</button>
        <button type="submit" class="btn btn-success" name="cmd"><i class="fa fa-check"></i>&nbsp;Save</button>
    </div>
}
<script src="~/Scripts/jquery.validate.min.js"></script>
<script>
    function FillSubCategory() {
        var cata_id = $('#Cata_ID').val();
        $.ajax({
            url: '/InventoryItem/FillSubCategory',
            type: "GET",
            dataType: "JSON",
            data: { cata_id: cata_id },
            success: function (subcategories) {
                $("#Subcata_ID").html(""); // clear before appending new list
                $.each(subcategories, function (i, sub) {
                    $("#Subcata_ID").append(
                        $('<option></option>').val(sub.Subcata_ID).html(sub.Subcata_Name));
                });
            }
        });
    }

    $('#itemAddForm').validate({
        rules: {
            Reorder_Level: {
                number: true,
            },
            Item_Name: "required"
        },
        messages: {            
            Reorder_Level: {
                number: "Reorder Lavel must be a number"
            },
            Item_Name: "Please provide the Item Name."
        }
    });

</script>

PMS_HT/Views/InventoryItem/Edit.cshtml
@model PMS_HT.Models.tbl_item

@using (Ajax.BeginForm("Edit", "InventoryItem", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "div-record", OnSuccess = "$('.close').click()" }))
{
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Item_ID)
    <div class="form-horizontal">
        <div class="modal-body">
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="row">
                <div class="form-group">
                    @Html.LabelFor(model => model.Cata_ID, "Category", htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-8">
                        @Html.DropDownList("Cata_ID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Cata_ID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Subcata_ID, "Sub Category", htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-8">
                        @Html.DropDownList("Subcata_ID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Subcata_ID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Brand_ID, "Brand ", htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-8">
                        @Html.DropDownList("Brand_ID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Brand_ID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Unit_ID, "Unit", htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-8">
                        @Html.DropDownList("Unit_ID", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Unit_ID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Item_Name, "Item Name", htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Item_Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Item_Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                @*<div class="form-group">
            @Html.LabelFor(model => model.Sales_Price, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.Sales_Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sales_Price, "", new { @class = "text-danger" })
            </div>
        </div>*@

                @*<div class="form-group">
                    @Html.LabelFor(model => model.Purchase_Price, "Purchase Price", htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-8">
                        @Html.EditorFor(model => model.Purchase_Price, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Purchase_Price, "", new { @class = "text-danger" })
                    </div>
                </div>*@

                <div class="form-group">
            @Html.LabelFor(model => model.Reorder_Level, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-8">
                @Html.EditorFor(model => model.Reorder_Level, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Reorder_Level, "", new { @class = "text-danger" })
            </div>
        </div>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i>&nbsp;Close</button>
        <button type="submit" class="btn btn-success" name="cmd"><i class="fa fa-check"></i>&nbsp;Save</button>
    </div>
}

PMS_HT/Views/InventoryItem/Index.cshtml
@model IEnumerable<PMS_HT.Models.tbl_item>
@{
    ViewBag.Title = "Item";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script src="~/Scripts/AddViewModel.js"></script>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="portlet box green">
                <div class="portlet-title">
                    <div class="caption">
                        <a href="@Url.Action("Add", "InventoryItem")" id="Add" class="btn default"><i class="glyphicon glyphicon-plus"></i>&nbsp;Add New Item</a>
                        Item
                    </div>
                    <div class="tools">

                    </div>
                </div>
                <div class="portlet-body">
                    <table class="table table-striped table-bordered table-hover" id="sample_2">
                        <thead>
                            <tr>
                                <th>SL No </th>                            
                                <th>Category </th>
                                <th>SubCategory </th>
                                <th>Brand</th>
                                <th>Unit</th>
                                <th>Item</th>
                                @*<th>Sales Price</th>*@
                                @*<th>Purchase Price</th>*@
                                <th>Reorder Level</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{ int i = 0;}
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @{i++;}
                                        @i
                                    </td>
                                 
                                    <td>
                                        @Html.DisplayFor(modelItem => item.tbl_category.Cata_Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.tbl_subcategory.Subcata_Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.tbl_brand.Brand_Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.tbl_unit.Unit_Name)
                                    </td>
                                    @{
                                        decimal remain_stock = Convert.ToDecimal(item.tbl_stock.Select(a => a.Stock_In).Sum() - item.tbl_stock.Select(a => a.Stock_Out).Sum());
                                        if (remain_stock > 0 && remain_stock <= item.Reorder_Level)
                                        {
                                            <td style="color:red;font-weight:700;">
                                                @item.Item_Name (@remain_stock)
                                            </td>
                                        }
                                        else if(remain_stock == 0)
                                        {
                                            <td>
                                                @item.Item_Name (@remain_stock)
                                            </td>
                                        }
                                        else
                                        {
                                            <td style="color:green;font-weight:700;">
                                                @item.Item_Name (@remain_stock)
                                            </td>
                                        }
                                    }
                                    @*<td>
                                        @Html.DisplayFor(modelItem => item.Sales_Price)
                                    </td>*@
                                    @*<td>
                                        @Html.DisplayFor(modelItem => item.Purchase_Price)
                                    </td>*@
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Reorder_Level)
                                    </td>
                                    <td>
                                        <a href="@Url.Action("Edit", "InventoryItem", new { id = item.Item_ID })" class="editDialog"><i class="fa fa-pencil-square-o"></i>&nbsp;Edit</a>
                                    </td>
                                    <td>
                                        @Ajax.ActionLink(" Delete", "Delete", "InventoryItem", new { @id = item.Item_ID }, new AjaxOptions { HttpMethod = "GET", UpdateTargetId = "div-record" }, new { onclick = "return confirm('Are you sure you wish to delete this Item?');", @class = "fa fa-trash-o" })
                                    </td>
                                </tr>
                                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="modal fade" id="Add-Model" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Add Item</h4>
            </div>
            <div class="divForAdd">
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="Edit-Model" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Update Item</h4>
            </div>
            <div class="divForUpdate">
            </div>
        </div>
    </div>
</div>

<script>
    $('.editDialog').click(function (event) {
        event.preventDefault();
        $.get(this.href, function (response) {
            $('.divForUpdate').html(response);
        });
        $('#Edit-Model').modal({
            backdrop: 'static',
        }, 'show');
    });
</script>