PMS_HT/Controllers/BanquetProgramController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using PMS_HT.Models;

namespace PMS_HT.Controllers
{
    public class BanquetProgramController : CustomControllerBase
    {
        public ActionResult Index()
        {
            var tbl_banquet_prog = db.tbl_banquet_prog.Include(t => t.tbl_banquet_info).Include(t => t.tbl_country);
            return View(tbl_banquet_prog.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_banquet_prog tbl_banquet_prog = db.tbl_banquet_prog.Find(id);
            if (tbl_banquet_prog == null)
            {
                return HttpNotFound();
            }
            return View(tbl_banquet_prog);
        }

        public ActionResult Add()
        {
            ViewBag.Banquet_ID = new SelectList(db.tbl_banquet_info, "Banquet_ID", "Banquet_Name");
            ViewBag.Country_ID = new SelectList(db.tbl_country, "Country_ID", "Country_Name");
            return PartialView();
        }

        [HttpPost]
        public ActionResult Add(tbl_banquet_prog program)
        {
            if (ModelState.IsValid)
            {
                db.tbl_banquet_prog.Add(program);
                db.SaveChanges();
            }
            ViewBag.Banquet_ID = new SelectList(db.tbl_banquet_info, "Banquet_ID", "Banquet_Name", program.Banquet_ID);
            ViewBag.Country_ID = new SelectList(db.tbl_country, "Country_ID", "Country_Name", program.Country_ID);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            tbl_banquet_prog program = db.tbl_banquet_prog.Find(id);
            ViewBag.Banquet_ID = new SelectList(db.tbl_banquet_info, "Banquet_ID", "Banquet_Name", program.Banquet_ID);
            ViewBag.Country_ID = new SelectList(db.tbl_country, "Country_ID", "Country_Name", program.Country_ID);
            return PartialView(program);
        }

        [HttpPost]
        public ActionResult Edit(tbl_banquet_prog program, int id)
        {
            if (ModelState.IsValid)
            {
                db.Entry(program).State = EntityState.Modified;
                db.SaveChanges();
            }
            ViewBag.Banquet_ID = new SelectList(db.tbl_banquet_info, "Banquet_ID", "Banquet_Name", program.Banquet_ID);
            ViewBag.Country_ID = new SelectList(db.tbl_country, "Country_ID", "Country_Name", program.Country_ID);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            db.tbl_banquet_prog.Remove(db.tbl_banquet_prog.Find(id));
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PMS_HT/Views/BanquetProgram/Add.cshtml
@model PMS_HT.Models.tbl_banquet_prog

@using (Ajax.BeginForm("Add", "BanquetProgram", new AjaxOptions { HttpMethod = "POST", UpdateTargetId = "div-record", OnSuccess = "$('.close').click()" }))
{

   
   
            <div class="form-horizontal">
                <div class="modal-body">
                    <div class="portlet-title tabbable-line">
                        <div class="caption caption-md">
                            <i class="icon-globe theme-font hide"></i>
          
                        </div>
                        <ul class="nav nav-tabs">
                            <li class="active">
                                <a href="#tab_1_1" data-toggle="tab">Guest Information</a>
                            </li>
                            <li>
                                <a href="#tab_1_2" data-toggle="tab">Company Information</a>
                            </li>
                        </ul>
                    </div>
                    <br />
                    <div class="tab-content">
                        <div class="tab-pane active" id="tab_1_1">
                            @Html.AntiForgeryToken()
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="row">
                                <div class="form-group">
                                    @Html.Label("Banquet", htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-8">
                                        @Html.DropDownList("Banquet_ID", null, htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Banquet_ID, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.Label("Person Name", htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-8">
                                        @Html.EditorFor(model => model.Person_Name, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Person_Name, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.Label("Person Adress", htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-8">
                                        @Html.EditorFor(model => model.Person_Adress, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Person_Adress, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Person_Phone, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-8">
                                        @Html.EditorFor(model => model.Person_Phone, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Person_Phone, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-8">
                                        @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-8">
                                        @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-8">
                                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                        </div>

                            <div class="tab-pane" id="tab_1_2">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Country_ID, "Country Name", htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-8">
                                        @Html.DropDownList("Country_ID", null, htmlAttributes: new { @class = "form-control" })
                                        @Html.ValidationMessageFor(model => model.Country_ID, "", new { @class = "text-danger" })
                                    </div>
                                </div>


                                <div class="form-group">
                                    @Html.LabelFor(model => model.Company_Name, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-8">
                                        @Html.EditorFor(model => model.Company_Name, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Company_Name, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Company_Adress, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-8">
                                        @Html.EditorFor(model => model.Company_Adress, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Company_Adress, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Company_Phone, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-8">
                                        @Html.EditorFor(model => model.Company_Phone, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Company_Phone, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Company_Details, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-8">
                                        @Html.EditorFor(model => model.Company_Details, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Company_Details, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Contact_Person, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-8">
                                        @Html.EditorFor(model => model.Contact_Person, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Contact_Person, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Contact_Person_Phone, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-8">
                                        @Html.EditorFor(model => model.Contact_Person_Phone, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Contact_Person_Phone, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Contact_Person_Address, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-8">
                                        @Html.EditorFor(model => model.Contact_Person_Address, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Contact_Person_Address, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                    </div>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal"><i class="fa fa-times"></i>&nbsp;Close</button>
            <button type="submit" class="btn btn-success" name="cmd"><i class="fa fa-check"></i>&nbsp;Save</button>
        </div>
        }

PMS_HT/Views/BanquetProgram/Details.cshtml
@model PMS_HT.Models.tbl_banquet_prog

@{
    ViewBag.Title = "Details";
}

<script src="~/Scripts/AddViewModel.js"></script>



<div>
  
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Banquet Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_banquet_info.Banquet_Name)
        </dd>

        <dt>
          Country Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tbl_country.Country_Name)
        </dd>

        <dt>
        Person Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person_Name)
        </dd>

        <dt>
            Person Address
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person_Adress)
        </dd>

        <dt>
            Person Phone
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Person_Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Company_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Company_Adress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company_Adress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Company_Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company_Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Company_Details)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Company_Details)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contact_Person)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contact_Person)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contact_Person_Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contact_Person_Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Contact_Person_Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contact_Person_Address)
        </dd>

    </dl>
</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.Program_ID }) |*@

    
        <a href="@Url.Action("Edit", "BanquetProgram", new { id = Model.Program_ID })" class="editDialog"></i>&nbsp;Edit</a>|
  
    @Html.ActionLink("Back to List", "Index")
</p>
<div class="modal fade" id="Add-Model" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">New Banquet Program</h4>
            </div>
            <div class="divForAdd">
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="Edit-Model" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Update Banquet Program</h4>
            </div>
            <div class="divForUpdate">
            </div>
        </div>
    </div>
</div>

PMS_HT/Views/BanquetProgram/Index.cshtml
@model IEnumerable<PMS_HT.Models.tbl_banquet_prog>

@{
    ViewBag.Title = "Banquet Program";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/AddViewModel.js"></script>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="portlet box green">
                <div class="portlet-title">
                    <div class="caption">
                        <a href="@Url.Action("Add", "BanquetProgram")" id="Add" class="btn default"><i class="glyphicon glyphicon-plus"></i>&nbsp;Create New</a>
                      Banquet Program
                    </div>
                    <div class="tools">

                    </div>
                </div>
                <div class="portlet-body">
                    <table class="table table-striped table-bordered table-hover" id="sample_2">
                        <thead>
                            <tr>
                                <th>SL No </th>
                                <th>Banquet Name</th>
                                <th>Person Name</th>
                                <th>Country Name</th>
                                 <th>Booking</th>
                             
                                <th>Edit</th>

                        
                                <th>Delete</th>
                                <th>Details</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{ int i = 0;}
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @{i++;}
                                        @i
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.tbl_banquet_info.Banquet_Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Person_Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.tbl_country.Country_Name)
                                    </td>
                                    <td>
                                        <a href="@Url.Action( "Index" ,"BanquetBooking" , new { id = item.Program_ID })" class="btn btn-success">
                                           Booking
                                        </a>
                                    </td>

                                
                                    @*@Html.ActionLink("Details", "Details", new { id = item.Room_ID }) |*@
                                    <td>
                                        <a href="@Url.Action("Edit", "BanquetProgram", new { id = item.Program_ID })" class="editDialog"><i class="fa fa-pencil-square-o"></i>&nbsp;Edit</a>
                                    </td>
                                   
                                    <td>
                                        @Ajax.ActionLink(" Delete", "Delete", "BanquetProgram", new { @id = item.Program_ID }, new AjaxOptions { HttpMethod = "GET", UpdateTargetId = "div-record" }, new { onclick = "return confirm('Are you sure you wish to delete this Benquet Booking?');", @class = "fa fa-trash-o" })
                                    </td>
                                    <td>@Html.ActionLink("Details", "Details", new { id = item.Program_ID })</td>
                                </tr>
                          }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>



<div class="modal fade" id="Add-Model" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">New Banquet Program</h4>
            </div>
            <div class="divForAdd">
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="Edit-Model" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Update Banquet Program</h4>
            </div>
            <div class="divForUpdate">
            </div>
        </div>
    </div>
</div>

<script>
    $('.editDialog').click(function (event) {
        event.preventDefault();
        $.get(this.href, function (response) {
            $('.divForUpdate').html(response);
        });
        $('#Edit-Model').modal({
            backdrop: 'static',
        }, 'show');
    });
</script>